### ISSUE TITLE
yolo detection demo运行闪退，找不到libhcl.so

### ISSUE THREAD

**Issue by tanzhiwei2000** [PaddlePaddle/Paddle-Lite-Demo#113]
2021-03-01 20:53:28.357 17938-17938/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.baidu.paddle.lite.demo.yolo_detection, PID: 17938
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libhcl.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.baidu.paddle.lite.demo.yolo_detection.Native.<clinit>(Native.java:7)
        at com.baidu.paddle.lite.demo.yolo_detection.MainActivity.<init>(MainActivity.java:42)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1180)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2907)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3103)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1804)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6913)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)

**Comment by wjhtinger** [comment]
我的也是，楼主解决了吗 ？

**Comment by lichen4321** [comment]
cmake里面把hcl的拷贝加上

**Comment by allchipiot** [comment]
> cmake里面把hcl的拷贝加上

可以说得详细一点吗？谢谢

**Comment by lichen4321** [comment]
add_custom_command(
        TARGET Native
        POST_BUILD
        COMMAND
        ${CMAKE_COMMAND} -E copy
        ${PaddleLite_DIR}/cxx/libs/${ANDROID_ABI}/libhcl.so
        ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}/libhcl.so)
