### ISSUE TITLE
android studio中得image_classification_demo编译报错

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/Paddle-Lite-Demo#117]
请大佬看到帮忙给指点下，谢了

![报错](https://user-images.githubusercontent.com/77316774/112812148-58e4d380-90af-11eb-9e76-70084ab1911c.jpg)

**Comment by gaorui999** [comment]
2021-03-29 19:39:12.060 21287-21287/? I/_classificatio: Late-enabling -Xcheck:jni
2021-03-29 19:39:12.086 21287-21287/? E/_classificatio: Unknown bits set in runtime_flags: 0x8000
2021-03-29 19:39:12.087 21287-21287/? I/_classificatio: Reinit property: dalvik.vm.checkjni= false
2021-03-29 19:39:12.100 21287-21287/com.baidu.paddle.lite.demo.image_classification E/libc: Access denied finding property "runtime.mmitest.isrunning"
2021-03-29 19:39:12.094 21287-21287/com.baidu.paddle.lite.demo.image_classification W/re-initialized>: type=1400 audit(0.0:4266915): avc: denied { read } for pid=21287 name="u:object_r:mmi_prop:s0" dev="tmpfs" ino=3927 scontext=u:r:untrusted_app_27:s0:c175,c256,c512,c768 tcontext=u:object_r:mmi_prop:s0 tclass=file permissive=0
2021-03-29 19:39:12.102 21287-21287/com.baidu.paddle.lite.demo.image_classification D/ActivityThread: Attach thread to application
2021-03-29 19:39:12.198 21287-21287/com.baidu.paddle.lite.demo.image_classification I/_classificatio: QarthPatchMonintor::Init
2021-03-29 19:39:12.198 21287-21287/com.baidu.paddle.lite.demo.image_classification I/_classificatio: QarthPatchMonintor::StartWatch
2021-03-29 19:39:12.198 21287-21287/com.baidu.paddle.lite.demo.image_classification I/_classificatio: QarthPatchMonintor::WatchPackage: /data/hotpatch/fwkhotpatch/
2021-03-29 19:39:12.198 21287-21287/com.baidu.paddle.lite.demo.image_classification I/_classificatio: QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/com.baidu.paddle.lite.demo.image_classification
2021-03-29 19:39:12.198 21287-21287/com.baidu.paddle.lite.demo.image_classification I/_classificatio: QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/all
2021-03-29 19:39:12.198 21287-21287/com.baidu.paddle.lite.demo.image_classification I/_classificatio: QarthPatchMonintor::Run
2021-03-29 19:39:12.198 21287-21324/com.baidu.paddle.lite.demo.image_classification I/_classificatio: QarthPatchMonintor::Reading
2021-03-29 19:39:12.198 21287-21324/com.baidu.paddle.lite.demo.image_classification I/_classificatio: QarthPatchMonintor::CheckNotifyEvent
2021-03-29 19:39:12.198 21287-21324/com.baidu.paddle.lite.demo.image_classification I/_classificatio: QarthPatchMonintor::CheckNotifyEvent before read
2021-03-29 19:39:12.198 21287-21306/com.baidu.paddle.lite.demo.image_classification I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.baidu.paddle.lite.demo.image_classification#10175#256
2021-03-29 19:39:12.199 21287-21306/com.baidu.paddle.lite.demo.image_classification I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.baidu.paddle.lite.demo.image_classification#10175#0
2021-03-29 19:39:12.203 21287-21306/com.baidu.paddle.lite.demo.image_classification I/AwareBitmapCacher: init processName:com.baidu.paddle.lite.demo.image_classification pid=21287 uid=10175
2021-03-29 19:39:12.206 21287-21327/com.baidu.paddle.lite.demo.image_classification E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@d0909f5
2021-03-29 19:39:12.207 21287-21287/com.baidu.paddle.lite.demo.image_classification D/OpenGLRenderer: disableOutlineDraw is true
2021-03-29 19:39:12.207 21287-21327/com.baidu.paddle.lite.demo.image_classification E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@660138a
2021-03-29 19:39:12.237 21287-21287/com.baidu.paddle.lite.demo.image_classification V/ActivityThread: callActivityOnCreate
2021-03-29 19:39:12.262 21287-21287/com.baidu.paddle.lite.demo.image_classification V/HwWidgetFactory: : successes to get AllImpl object and return....
2021-03-29 19:39:12.277 21287-21287/com.baidu.paddle.lite.demo.image_classification I/OverScrollerOptimization: start init SmartSlideOverScroller and get the overscroller config
2021-03-29 19:39:12.277 21287-21287/com.baidu.paddle.lite.demo.image_classification I/OverScrollerOptimization: get the overscroller config
2021-03-29 19:39:12.309 21287-21287/com.baidu.paddle.lite.demo.image_classification W/_classificatio: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2021-03-29 19:39:12.310 21287-21287/com.baidu.paddle.lite.demo.image_classification W/_classificatio: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2021-03-29 19:39:12.353 21287-21287/com.baidu.paddle.lite.demo.image_classification D/ActivityThread: add activity client record, r= ActivityRecord{9a9ff8c token=android.os.BinderProxy@b02a2df {com.baidu.paddle.lite.demo.image_classification/com.baidu.paddle.lite.demo.image_classification.MainActivity}} token= android.os.BinderProxy@b02a2df
2021-03-29 19:39:12.408 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err: java.io.FileNotFoundException: /data/user/0/com.baidu.paddle.lite.demo.image_classification/cache/models/model/model.nb: open failed: EISDIR (Is a directory)
2021-03-29 19:39:12.408 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:496)
2021-03-29 19:39:12.408 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
2021-03-29 19:39:12.408 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
2021-03-29 19:39:12.408 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at com.baidu.paddle.lite.demo.image_classification.Utils.copyFileFromAssets(Utils.java:19)
2021-03-29 19:39:12.408 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at com.baidu.paddle.lite.demo.image_classification.Utils.copyDirectoryFromAssets(Utils.java:53)
2021-03-29 19:39:12.408 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at com.baidu.paddle.lite.demo.image_classification.Predictor.loadModel(Predictor.java:106)
2021-03-29 19:39:12.409 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at com.baidu.paddle.lite.demo.image_classification.Predictor.init(Predictor.java:78)
2021-03-29 19:39:12.409 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at com.baidu.paddle.lite.demo.image_classification.MainActivity.onLoadModel(MainActivity.java:231)
2021-03-29 19:39:12.409 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at com.baidu.paddle.lite.demo.image_classification.MainActivity$2.handleMessage(MainActivity.java:123)
2021-03-29 19:39:12.409 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2021-03-29 19:39:12.409 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at android.os.Looper.loop(Looper.java:213)
2021-03-29 19:39:12.409 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)
2021-03-29 19:39:12.411 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err: Caused by: android.system.ErrnoException: open failed: EISDIR (Is a directory)
2021-03-29 19:39:12.411 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at libcore.io.Linux.open(Native Method)
2021-03-29 19:39:12.411 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
2021-03-29 19:39:12.411 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
2021-03-29 19:39:12.411 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
2021-03-29 19:39:12.411 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8046)
2021-03-29 19:39:12.411 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:482)
2021-03-29 19:39:12.411 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err: 	... 11 more
2021-03-29 19:39:12.411 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.close()' on a null object reference
2021-03-29 19:39:12.412 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at com.baidu.paddle.lite.demo.image_classification.Utils.copyFileFromAssets(Utils.java:31)
2021-03-29 19:39:12.412 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at com.baidu.paddle.lite.demo.image_classification.Utils.copyDirectoryFromAssets(Utils.java:53)
2021-03-29 19:39:12.412 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at com.baidu.paddle.lite.demo.image_classification.Predictor.loadModel(Predictor.java:106)
2021-03-29 19:39:12.412 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at com.baidu.paddle.lite.demo.image_classification.Predictor.init(Predictor.java:78)
2021-03-29 19:39:12.412 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at com.baidu.paddle.lite.demo.image_classification.MainActivity.onLoadModel(MainActivity.java:231)
2021-03-29 19:39:12.412 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at com.baidu.paddle.lite.demo.image_classification.MainActivity$2.handleMessage(MainActivity.java:123)
2021-03-29 19:39:12.412 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2021-03-29 19:39:12.412 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at android.os.Looper.loop(Looper.java:213)
2021-03-29 19:39:12.412 21287-21332/com.baidu.paddle.lite.demo.image_classification W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)
2021-03-29 19:39:12.418 21287-21328/com.baidu.paddle.lite.demo.image_classification D/OpenGLRenderer: disableOutlineDraw is true
2021-03-29 19:39:12.426 21287-21332/com.baidu.paddle.lite.demo.image_classification I/AI_FMK: /initializer.cpp Init(45)::"load cl libs:libcpucl.so"
2021-03-29 19:39:12.434 21287-21328/com.baidu.paddle.lite.demo.image_classification I/iGraphics: [0020080c] pn: com.baidu.paddle.lite.demo.image_classification, p: 21287
2021-03-29 19:39:12.434 21287-21328/com.baidu.paddle.lite.demo.image_classification I/iGraphics: [0030050c] PV 10
2021-03-29 19:39:12.434 21287-21328/com.baidu.paddle.lite.demo.image_classification I/iGraphics: [0030050c] no element 'igfx'
2021-03-29 19:39:12.435 21287-21333/com.baidu.paddle.lite.demo.image_classification D/HiTouch_PressGestureDetector: onAttached, package=com.baidu.paddle.lite.demo.image_classification, windowType=2, mHiTouchRestricted=false
2021-03-29 19:39:12.439 21287-21328/com.baidu.paddle.lite.demo.image_classification I/iGraphics: [0030050c] LoadCloudParams lib file success.
2021-03-29 19:39:12.439 21287-21328/com.baidu.paddle.lite.demo.image_classification E/Parcel: Reading a NULL string not supported here.
2021-03-29 19:39:12.441 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.441 ...ang/Paddle-Lite/lite/core/device_info.cc:1065 Setup] ARM multiprocessors name: MODEL NAME	: ARMV8 PROCESSOR REV 4 (V8L)
    HARDWARE	: HISILICON KIRIN970
    _EML_KIRIN970_
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.441 ...ang/Paddle-Lite/lite/core/device_info.cc:1066 Setup] ARM multiprocessors number: 8
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 0, max freq: 1844, min freq: 1844, cluster ID: 1, CPU ARCH: A53
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 1, max freq: 1844, min freq: 1844, cluster ID: 1, CPU ARCH: A53
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 2, max freq: 1844, min freq: 1844, cluster ID: 1, CPU ARCH: A53
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 3, max freq: 1844, min freq: 1844, cluster ID: 1, CPU ARCH: A53
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 4, max freq: 2362, min freq: 2362, cluster ID: 0, CPU ARCH: A73
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 5, max freq: 2362, min freq: 2362, cluster ID: 0, CPU ARCH: A73
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 6, max freq: 2362, min freq: 2362, cluster ID: 0, CPU ARCH: A73
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1068 Setup] ARM multiprocessors ID: 7, max freq: 2362, min freq: 2362, cluster ID: 0, CPU ARCH: A73
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1074 Setup] L1 DataCache size is: 
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 32 KB
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/chatty: uid=10175(com.baidu.paddle.lite.demo.image_classification) Predictor Worke identical 6 lines
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1076 Setup] 32 KB
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1078 Setup] L2 Cache size is: 
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 512 KB
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/chatty: uid=10175(com.baidu.paddle.lite.demo.image_classification) Predictor Worke identical 6 lines
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1080 Setup] 512 KB
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1082 Setup] L3 Cache size is: 
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 0 KB
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/chatty: uid=10175(com.baidu.paddle.lite.demo.image_classification) Predictor Worke identical 6 lines
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1084 Setup] 0 KB
2021-03-29 19:39:12.442 21287-21332/com.baidu.paddle.lite.demo.image_classification I/Paddle-Lite: [I  3/29 19:39:12.442 ...ang/Paddle-Lite/lite/core/device_info.cc:1086 Setup] Total memory: 5802228KB
2021-03-29 19:39:12.443 21287-21332/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 19:39:12.443 ...Lite/lite/model_parser/flatbuffers/io.cc:41 LoadFile] Check failed: (fread(buf.data(), 1, length, file) == length): 0!==2 
2021-03-29 19:39:12.443 21287-21332/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 19:39:12.443 ...Lite/lite/model_parser/flatbuffers/io.cc:41 LoadFile] Check failed: (fread(buf.data(), 1, length, file) == length): 0!==2 
2021-03-29 19:39:12.443 21287-21332/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 19:39:12.443 ...e-Lite/lite/model_parser/model_parser.cc:862 LoadModelNaiveFromFile] Paddle-Lite v2.7 has upgraded the naive-buffer model format. Please use the OPT to generate a new model. Thanks!
2021-03-29 19:39:12.443 21287-21332/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 19:39:12.443 ...e-Lite/lite/model_parser/model_parser.cc:862 LoadModelNaiveFromFile] Paddle-Lite v2.7 has upgraded the naive-buffer model format. Please use the OPT to generate a new model. Thanks!
2021-03-29 19:39:12.443 21287-21332/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 19:39:12.443 ...ngyang/Paddle-Lite/lite/api/light_api.cc:146 BuildRuntimeProgram] Check failed: block_size: 
2021-03-29 19:39:12.443 21287-21332/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 19:39:12.443 ...ngyang/Paddle-Lite/lite/api/light_api.cc:146 BuildRuntimeProgram] Check failed: block_size: 
2021-03-29 19:39:12.443 21287-21332/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 19:39:12.443 ...engyang/Paddle-Lite/lite/core/program.cc:173 RuntimeProgram] Check failed: block_size: No block found!
2021-03-29 19:39:12.443 21287-21332/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 19:39:12.443 ...engyang/Paddle-Lite/lite/core/program.cc:173 RuntimeProgram] Check failed: block_size: No block found!
2021-03-29 19:39:12.443 21287-21332/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 19:39:12.443 ...engyang/Paddle-Lite/lite/core/program.cc:174 RuntimeProgram] Check failed: block_idx >= 0 && block_idx < block_size: Invalid block index, expected [0,4294967295] but got 0
2021-03-29 19:39:12.443 21287-21332/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 19:39:12.443 ...engyang/Paddle-Lite/lite/core/program.cc:174 RuntimeProgram] Check failed: block_idx >= 0 && block_idx < block_size: Invalid block index, expected [0,4294967295] but got 0
2021-03-29 19:39:12.443 21287-21332/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 19:39:12.443 ...model_parser/flatbuffers/program_desc.cc:31 GetBlock<paddle::lite::fbs::BlockDescView>] Check failed: (idx < static_cast<int32_t>(BlocksSize())): 0!<0 idx >= blocks.size()
2021-03-29 19:39:12.443 21287-21332/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 19:39:12.443 ...model_parser/flatbuffers/program_desc.cc:31 GetBlock<paddle::lite::fbs::BlockDescView>] Check failed: (idx < static_cast<int32_t>(BlocksSize())): 0!<0 idx >= blocks.size()
    
    
    
    --------- beginning of crash
2021-03-29 19:39:12.443 21287-21332/com.baidu.paddle.lite.demo.image_classification A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 21332 (Predictor Worke), pid 21287 (_classification)
2021-03-29 19:39:12.461 21287-21328/com.baidu.paddle.lite.demo.image_classification D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2021-03-29 19:39:12.468 21287-21328/com.baidu.paddle.lite.demo.image_classification W/Gralloc3: mapper 3.x is not supported
2021-03-29 19:39:12.593 21287-21361/com.baidu.paddle.lite.demo.image_classification D/HiTouch_PressGestureDetector: onAttached, package=com.baidu.paddle.lite.demo.image_classification, windowType=1, mHiTouchRestricted=false
2021-03-29 19:39:12.618 21287-21328/com.baidu.paddle.lite.demo.image_classification D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2021-03-29 19:39:12.642 21287-21287/com.baidu.paddle.lite.demo.image_classification I/HwViewRootImpl: removeInvalidNode jank list is null
2021-03-29 19:39:12.646 21287-21328/com.baidu.paddle.lite.demo.image_classification D/OpenGLRenderer: disableOutlineDraw is true

**Comment by gaorui999** [comment]
2021-03-29 21:44:51.291 22882-22922/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 21:44:51.291 ...e-Lite/lite/model_parser/model_parser.cc:871 LoadModelNaiveFromFile] The model format cannot be recognized. Please make sure you use the correct interface and model file.
2021-03-29 21:44:51.291 22882-22922/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 21:44:51.291 ...e-Lite/lite/model_parser/model_parser.cc:871 LoadModelNaiveFromFile] The model format cannot be recognized. Please make sure you use the correct interface and model file.
2021-03-29 21:44:51.291 22882-22922/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 21:44:51.291 ...ngyang/Paddle-Lite/lite/api/light_api.cc:146 BuildRuntimeProgram] Check failed: block_size: 
2021-03-29 21:44:51.291 22882-22922/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 21:44:51.291 ...ngyang/Paddle-Lite/lite/api/light_api.cc:146 BuildRuntimeProgram] Check failed: block_size: 
2021-03-29 21:44:51.291 22882-22922/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 21:44:51.291 ...engyang/Paddle-Lite/lite/core/program.cc:173 RuntimeProgram] Check failed: block_size: No block found!
2021-03-29 21:44:51.291 22882-22922/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 21:44:51.291 ...engyang/Paddle-Lite/lite/core/program.cc:173 RuntimeProgram] Check failed: block_size: No block found!
2021-03-29 21:44:51.291 22882-22922/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 21:44:51.291 ...engyang/Paddle-Lite/lite/core/program.cc:174 RuntimeProgram] Check failed: block_idx >= 0 && block_idx < block_size: Invalid block index, expected [0,4294967295] but got 0
2021-03-29 21:44:51.291 22882-22922/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 21:44:51.291 ...engyang/Paddle-Lite/lite/core/program.cc:174 RuntimeProgram] Check failed: block_idx >= 0 && block_idx < block_size: Invalid block index, expected [0,4294967295] but got 0
2021-03-29 21:44:51.291 22882-22922/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 21:44:51.291 ...model_parser/flatbuffers/program_desc.cc:31 GetBlock<paddle::lite::fbs::BlockDescView>] Check failed: (idx < static_cast<int32_t>(BlocksSize())): 0!<0 idx >= blocks.size()
2021-03-29 21:44:51.291 22882-22922/com.baidu.paddle.lite.demo.image_classification A/Paddle-Lite: [F  3/29 21:44:51.291 ...model_parser/flatbuffers/program_desc.cc:31 GetBlock<paddle::lite::fbs::BlockDescView>] Check failed: (idx < static_cast<int32_t>(BlocksSize())): 0!<0 idx >= blocks.size()
    
    
    
    --------- beginning of crash
2021-03-29 21:44:51.292 22882-22922/com.baidu.paddle.lite.demo.image_classification A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 22922 (Predictor Worke), pid 22882 (_classification)

**Comment by cha0cha0** [comment]
可以先看下这个链接里面的demo代码结构解析：https://paddle-lite.readthedocs.io/zh/latest/demo_guides/android_app_demo.html#id1；其中转换模型nb文件的opt版本需要和demo的so库版本保持一致。可以尝试下用这个帖子重新编译生成so：https://paddle-lite.readthedocs.io/zh/latest/source_compile/compile_andriod.html。
之后用同一个paddle lite版本的转换的nb和so替换原始demo对应的文件。
