### ISSUE TITLE
mask_detection libpaddle_light_api_shared.so

### ISSUE THREAD

**Issue by premeditate** [PaddlePaddle/Paddle-Lite-Demo#199]
下载了项目代码,使用Androidstudio3.5打开,cmake3.10.2,NDK20.0,进行编译,编译完成后能正常部署到Android平板中(HUAWEI mate PAD10.8 Android10).但是程序启动总是闪退,在AS(Androidstudio)中并没有程序崩溃的日志.

提示:Waiting for process to come online...,然后Timed out waiting for process to appear on huawei-scmr_w09...

在logcat中Error日志中看到如下错误日志: 
Process: com.baidu.paddle.lite.demo.mask_detection, PID: 10267
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libpaddle_light_api_shared.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at com.baidu.paddle.lite.demo.mask_detection.Native.<clinit>(Native.java:7)
        at com.baidu.paddle.lite.demo.mask_detection.MainActivity.<init>(MainActivity.java:41)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at android.support.v4.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1264)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3801)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by premeditate** [comment]
不能使用Androidstudio3.5,在AS3.5中虽然能编译程序并发布,但是运行时会有问题,因为这个程序默认使用的是gradle-7.0,而在AS3.5中不能使用gradle-7.0,gradle-7.0需要更新版本的AS支持,所以安装新版AS,笔者安装Android Studio Bumblebee | 2021.1.1 Patch 2,运行这个程序就没有这个问题了
