### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libpaddle_light_api_shared.so" not found

### ISSUE THREAD

**Issue by premeditate** [PaddlePaddle/Paddle-Lite-Demo#251]
运行在Android 10 pad,启动应用闪退并伴随这个错误(Run on Android 10 pad, start the application and flash back with this error)

2022-05-05 14:51:01.273 5763-5763/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.baidu.paddle.lite.demo.ssd_detection, PID: 5763
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libpaddle_light_api_shared.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at com.baidu.paddle.lite.demo.object_detection.Native.<clinit>(Native.java:7)
        at com.baidu.paddle.lite.demo.object_detection.MainActivity.<init>(MainActivity.java:40)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at android.support.v4.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1264)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3801)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by premeditate** [comment]
Android studio 3.5.2

gradle-wrapper.properties
    distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

build.gradle
    dependencies{
        classpath 'com.android.tools.build:gradle:3.5.2'
    }

ndk
    D:\AndroidSDK\ndk\21.1.6352462

cmake
    3.10.2

pad
    Android 10

**Comment by premeditate** [comment]
这个环境,能够编译成功,并且发布在平板上,平板上运行时就程序闪退,在logcat中出现上述错误(This environment can be compiled successfully and released on the tablet. When running on the tablet, the program will flash back, and the above error occurs in logcat)

**Comment by chenjiaoAngel** [comment]
这个错误是找不到正确的SO 位置：
<img width="675" alt="image" src="https://user-images.githubusercontent.com/38650344/167330059-e7f55fa2-c031-47c7-9e01-993af9726dc7.png">
这个SO 一般会打包到SDK/APP 里，放到手机目录下进行运行。
你是否有修改工程？在Android 手机有测试，是否能运行

**Comment by premeditate** [comment]
不能使用Androidstudio3.5,在AS3.5中虽然能编译程序并发布,但是运行时会有问题,因为这个程序默认使用的是gradle-7.0,而在AS3.5中不能使用gradle-7.0,gradle-7.0需要更新版本的AS支持,所以安装新版AS,笔者安装Android Studio Bumblebee | 2021.1.1 Patch 2,运行这个程序就没有这个问题了
