### ISSUE TITLE
运行以后报错，但是生成了app，打开就闪退

### ISSUE THREAD

**Issue by MRZHANG-1997** [PaddlePaddle/Paddle-Lite-Demo#330]
E/AndroidRuntime: FATAL EXCEPTION: Predictor Worker
    Process: com.baidu.paddle.lite.demo.image_classification, PID: 4451
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.baidu.paddle.lite.demo.image_classification-1/base.apk"],nativeLibraryDirectories=[/data/app/com.baidu.paddle.lite.demo.image_classification-1/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libpaddle_lite_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
        at java.lang.System.loadLibrary(System.java:1562)
        at com.baidu.paddle.lite.PaddleLiteInitializer.init(PaddleLiteInitializer.java:20)
        at com.baidu.paddle.lite.PaddlePredictor.<clinit>(PaddlePredictor.java:197)
        at com.baidu.paddle.lite.PaddlePredictor.createPaddlePredictor(PaddlePredictor.java:41)
        at com.baidu.paddle.lite.demo.image_classification.Predictor.loadModel(Predictor.java:131)
        at com.baidu.paddle.lite.demo.image_classification.Predictor.init(Predictor.java:78)
        at com.baidu.paddle.lite.demo.image_classification.MainActivity.onLoadModel(MainActivity.java:231)
        at com.baidu.paddle.lite.demo.image_classification.MainActivity$2.handleMessage(MainActivity.java:123)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
I/Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
E/WindowManager: android.view.WindowLeaked: Activity com.baidu.paddle.lite.demo.image_classification.MainActivity has leaked window DecorView@43a3ae7[] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.app.Dialog.show(Dialog.java:329)
        at android.app.ProgressDialog.show(ProgressDialog.java:116)
        at android.app.ProgressDialog.show(ProgressDialog.java:104)
        at com.baidu.paddle.lite.demo.image_classification.MainActivity.loadModel(MainActivity.java:221)
        at com.baidu.paddle.lite.demo.image_classification.MainActivity.onResume(MainActivity.java:216)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
        at android.app.Activity.performResume(Activity.java:6796)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3472)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2735)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6176)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by Digital2Slave** [comment]
`[/data/app/com.baidu.paddle.lite.demo.image_classification-1/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libpaddle_lite_jni.so"`

- create `jniLibs` in **app/src/main/**  folder.
- copy `cxx/libs/${ANDROID_ABI}` folder to `jniLibs` folder.
