### ISSUE TITLE
Camera Preview demo, ssd_detection_demo keeps stopping

### ISSUE THREAD

**Issue by StevenJokes** [PaddlePaddle/Paddle-Lite-Demo#84]
![image](https://user-images.githubusercontent.com/25657787/88533152-5cafea00-d038-11ea-833e-6271c327b56f.png)

---
```
2020-07-27 18:42:55.461 7101-7101/? I/ra_preview_dem: Not late-enabling -Xcheck:jni (already on)
2020-07-27 18:42:55.486 7101-7101/? I/ra_preview_dem: Unquickening 12 vdex files!
2020-07-27 18:42:55.488 7101-7101/? W/ra_preview_dem: Unexpected CPU variant for X86 using defaults: x86
2020-07-27 18:42:55.577 7101-7101/com.baidu.paddle.lite.demo.camera_preview_demo D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
2020-07-27 18:42:55.670 7101-7101/com.baidu.paddle.lite.demo.camera_preview_demo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-07-27 18:42:55.671 7101-7101/com.baidu.paddle.lite.demo.camera_preview_demo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-07-27 18:42:55.691 7101-7126/com.baidu.paddle.lite.demo.camera_preview_demo D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
2020-07-27 18:42:55.693 7101-7126/com.baidu.paddle.lite.demo.camera_preview_demo D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
2020-07-27 18:42:55.694 7101-7101/com.baidu.paddle.lite.demo.camera_preview_demo D/AndroidRuntime: Shutting down VM

2020-07-27 18:42:55.695 7101-7101/com.baidu.paddle.lite.demo.camera_preview_demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.baidu.paddle.lite.demo.camera_preview_demo, PID: 7101
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libNative.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.baidu.paddle.lite.demo.camera_preview.Native.<clinit>(Native.java:7)
        at com.baidu.paddle.lite.demo.camera_preview.MainActivity.<init>(MainActivity.java:37)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at android.support.v4.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

2020-07-27 18:42:55.697 7101-7126/com.baidu.paddle.lite.demo.camera_preview_demo D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
```
---

Other demo, such as imagation detection demo run well
![image](https://user-images.githubusercontent.com/25657787/88533264-941e9680-d038-11ea-960b-950c4658b354.png)
![image](https://user-images.githubusercontent.com/25657787/88552481-baebc580-d056-11ea-903a-38df305405a9.png)

**Comment by StevenJokes** [comment]
Gradle 从3.2.0改到4.0.0,
从5.1.1到6.1.1也不管用。
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip

**Comment by StevenJokes** [comment]
2020-07-27 22:21:52.024 736-2762/? E/LOGSERVER_UTILS: [Erecovery]readEvent: eRecEventManager readEvent 0
2020-07-27 22:21:53.064 736-2762/? E/LOGSERVER_UTILS: [Erecovery]readEvent: eRecEventManager readEvent 0

**Comment by zhupengyang** [comment]
Camera Preview demo是用来测试摄像头功能的，是不跑paddlelite模型的。看上去你是用的Android模拟器，可能没有摄像头功能，所以就挂了？

**Comment by StevenJokes** [comment]
跟模拟器的摄像没关系，模拟器有假的摄像模拟。。
![image](https://user-images.githubusercontent.com/25657787/89026358-2a193080-d35b-11ea-8d77-b8016788dc86.png)

**Comment by StevenJokes** [comment]
ssd_detection_demo也存在这样的问题？？

2020-08-03 23:42:01.059 12698-12698/com.baidu.paddle.lite.demo.ssd_detection D/AndroidRuntime: Shutting down VM
2020-08-03 23:42:01.067 12698-12698/com.baidu.paddle.lite.demo.ssd_detection E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.baidu.paddle.lite.demo.ssd_detection, PID: 12698
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libNative.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.baidu.paddle.lite.demo.ssd_detection.Native.<clinit>(Native.java:7)
        at com.baidu.paddle.lite.demo.ssd_detection.MainActivity.<init>(MainActivity.java:42)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at android.support.v4.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by StevenJokes** [comment]
后来发现是https://github.com/android/ndk-samples/issues/450里提到
+        ndk {
+            abiFilters 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'arm64-v8a'
+        }
与实际项目中
![image](https://user-images.githubusercontent.com/25657787/89201634-64e1c980-d5e4-11ea-98db-d479dffe35a2.png)
是架构问题，换到真实手机就解决了。
