### ISSUE TITLE
failed: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libhiai_ir.so"

### ISSUE THREAD

**Issue by RussellUS** [PaddlePaddle/Paddle-Lite-Demo#85]
Paddle-Lite-Demo-master\PaddleLite-android-demo\mask_detection_demo在android5.1.1系统运行失败，并报错：
08-17 15:46:00.825 2166-2166/? E/art: dlopen("/data/app/com.baidu.paddle.lite.demo.mask_detection-1/lib/arm/libNative.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libhiai_ir.so"...
08-17 15:46:00.826 2166-2166/? D/AndroidRuntime: Shutting down VM
08-17 15:46:00.827 2166-2166/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.baidu.paddle.lite.demo.mask_detection, PID: 2166
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libhiai_ir.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:988)
        at com.baidu.paddle.lite.demo.mask_detection.Native.<clinit>(Native.java:7)
        at com.baidu.paddle.lite.demo.mask_detection.MainActivity.<init>(MainActivity.java:40)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.Class.newInstance(Class.java:1606)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2242)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2407)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5280)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
软硬件环境：
rk3288，android5.1.1，ndk-r21.
但是，完全同样的demo运行在android8.1上没有上述错误。

**Comment by hong19860320** [comment]
是的，由于华为hiai要求 API LEVEL为24 也就是android 7.0，因此，android 5.1可能会发生这个问题，解决版本是修改https://github.com/PaddlePaddle/Paddle-Lite/blob/4a6499a617c618f4971004c20c5c83f4097492ef/cmake/cross_compiling/android.cmake#L36
将所有api level改成21
